[package]
name = "video-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-multipart="0.5"
futures-util = "0.3"
derive_more = "0.99.0"
mime = "0.3.16"
