version: "3.8"

services:
  database:
    image: mongo:6
    ports:
      - "27017:27017"
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://database:27017
    depends_on:
      - database
